CREATE TABLE "AutoCleanupPolicy" (
  "id" INTEGER NOT NULL DEFAULT 1,
  "enabled" BOOLEAN NOT NULL DEFAULT false,
  "maxAgeDays" INTEGER NOT NULL DEFAULT 30,
  "excludeFavorited" BOOLEAN NOT NULL DEFAULT true,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "AutoCleanupPolicy_pkey" PRIMARY KEY ("id")
);
