ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'DOWNLOAD';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'SHARE';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGIN';
ALTER TYPE "AuditAction" ADD VALUE IF NOT EXISTS 'LOGOUT';
